#!/bin/sh
# Assemble the section files into a single research plan.
#   sh 03-research-plan/draft/assemble.sh
# Output: 03-research-plan/FINAL-research-plan.md
DIR="$(dirname "$0")"
OUT="$DIR/../FINAL-research-plan.md"
{
  cat <<'HDR'
> **Assembled document — do not edit here.**
> Generated by `draft/assemble.sh` from the section files in `draft/`. Edit those, then re-run.
> Figures are in `draft/figures/` (regenerate with `python3 draft/figures/make_figures.py`).
> Bibliography is `draft/99-bibliography.md`, excluded from the character count.

---

HDR
  for f in "$DIR"/00-*.md "$DIR"/01-*.md "$DIR"/02-*.md "$DIR"/03-*.md \
           "$DIR"/04-*.md "$DIR"/05-*.md "$DIR"/06-*.md; do
      cat "$f"; printf '\n\n---\n\n'
  done
  cat "$DIR/99-bibliography.md"
} > "$OUT"
echo "wrote $OUT"
sh "$DIR/wordcount.sh" | tail -3
